### ISSUE TITLE
\editAnnouncement API bugs

### ISSUE THREAD

**Issue by akhil-maddukuri** [BHAVANA1497/GatorDesk#17]
End of exception occurred for a few test cases.

**Comment by Nitya-vaishnavi** [comment]
@akhil-maddukuri Could you please be more specific?

**Comment by akhil-maddukuri** [comment]
I'm encountering an End of File Error when I am trying to update an announcement whose announcement_Id is not there in the Announcement table

![Testcase 12 error image](https://user-images.githubusercontent.com/46106443/152605617-e6757aba-c303-484e-8294-086763c6ebae.jpeg)

**Comment by akhil-maddukuri** [comment]
Sure, I'm working on it

**Comment by akhil-maddukuri** [comment]
Fixed!

**Comment by Nitya-vaishnavi** [comment]
Verified! We can close the issue now
