### ISSUE TITLE
Create User Registration functionality

### ISSUE THREAD

**Issue by akhil-maddukuri** [BHAVANA1497/GatorDesk#34]

**Comment by Nitya-vaishnavi** [comment]
@akhil-maddukuri I have created the API and tested for some borderline cases. Screenshot attached.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/43131417/156860727-113c01dc-759f-4257-8dfb-c8b245d24bcf.png">

Could you please test vigorously?
